# Generated by Django 3.2.4 on 2021-06-13 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred_app', '0005_alter_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='balance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
