# Generated by Django 3.2.4 on 2021-06-13 11:33

import django.core.validators
from django.db import migrations, models
import pred_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pred_app', '0006_alter_portfolio_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_before',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='balance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), pred_app.models.validate_decimals]),
        ),
    ]
