# Generated by Django 3.2.4 on 2021-06-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred_app', '0008_popularstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularstock',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='popularstock',
            name='symbol',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
